In [2]:
import numpy as np

# Array vs Lists

In [3]:
x=range(500)
y=np.arange(500) #equivalent of x in numpy
print(x)
print(y)

range(0, 500)
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 

In [42]:
x=np.arange(12).reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
list=[1,2,3,4]
arr=np.array([1,2,3,4])
print(list)
arr

[1, 2, 3, 4]


array([1, 2, 3, 4])

# Array memory representation

In [9]:
x=np.array([[1,2],[5,6]])
x.dtype

dtype('int64')

In [14]:
x=np.array([[2.0,3],[4,8]])
print(x)
x.dtype

[[2. 3.]
 [4. 8.]]


dtype('float64')

In [15]:
np.iinfo('int64')

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [16]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [18]:
x=np.array([0,127,255],dtype=np.uint8) #x contains numbers ranging from 0 to 255 only.
print(x)

[  0 127 255]


In [19]:
x+1

array([  1, 128,   0], dtype=uint8)

In [20]:
x-1

array([255, 126, 254], dtype=uint8)

# Array creation

In [21]:
np.zeros((3,4),dtype=float)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.zeros((3),dtype=complex)

array([0.+0.j, 0.+0.j, 0.+0.j])

In [24]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [27]:
np.empty((2,3)) #These are random memory entries!

array([[5.29170744e+174, 7.55922911e-067, 1.74121810e+184],
       [1.35049577e+161, 5.01163193e+217, 5.49419094e-143]])

In [29]:
np.linspace(0,1,5) #start,stop,num

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [32]:
np.logspace(1,4,4)

array([   10.,   100.,  1000., 10000.])

In [34]:
rng=np.random.RandomState(0) #Create number generator according to various distributions
print(rng)

In [35]:
rng.uniform(low=1,high=5,size=50) #Uniform distribution

array([3.19525402, 3.86075747, 3.4110535 , 3.17953273, 2.6946192 ,
       3.58357645, 2.75034885, 4.567092  , 4.85465104, 2.53376608,
       4.16690015, 3.11557968, 3.27217824, 4.70238655, 1.28414423,
       1.3485172 , 1.08087359, 4.33047938, 4.112627  , 4.48004859,
       4.91447337, 4.19663426, 2.84591745, 4.12211671, 1.4730977 ,
       3.55968409, 1.57341315, 4.77867567, 3.08739329, 2.65864776,
       2.05822245, 4.09693476, 2.82460133, 3.2737358 , 1.0751592 ,
       3.47054199, 3.44838289, 3.46773599, 4.77499231, 3.7272812 ,
       2.4380316 , 2.74812782, 3.79052478, 1.24090189, 3.66706686,
       3.68255148, 1.84153024, 1.51570519, 2.2617134 , 2.45484308])

In [36]:
rng.normal(loc=5,scale=1,size=5) #Normal distributiom

array([3.29372981, 6.9507754 , 4.49034782, 4.5619257 , 3.74720464])

# Array copies, references

In [37]:
a=np.array([1,3,4.6,2,1])
b=a
a

array([1. , 3. , 4.6, 2. , 1. ])

In [39]:
#changing third entry of b also changes third entry of a!
b[2]=27
print(a)
print(b)

[ 1.  3. 27.  2.  1.]
[ 1.  3. 27.  2.  1.]


In [40]:
#To copy a numpy array, use np.copy
c=np.copy(a)
c

array([ 1.,  3., 27.,  2.,  1.])

In [41]:
c[-1]=5.7
print(c)
print(a)

[ 1.   3.  27.   2.   5.7]
[ 1.  3. 27.  2.  1.]


In [44]:
p=np.arange(12).reshape((3,4))
p

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
np.sum(p)

66

In [46]:
np.sum(p,axis=0)

array([12, 15, 18, 21])

In [48]:
np.sum(p,axis=1)

array([ 6, 22, 38])